### ISSUE TITLE
QOS

### ISSUE THREAD

**Issue by jreyes256** [Lillecarl/ROS_Scripts#5]
Do you have any script for advanced service quality by services and by clients?

**Comment by Lillecarl** [comment]
Sadly i don't, i'll try putting something together. We need something ourselves too.

**Comment by Lillecarl** [comment]
@viptampa I've been looking into QoS, but on my weak devices that i've got at home (hAP AC) it doesn't really make sense to throttle my 100/100 even for testing, it'll spike the CPU and kill latency bigtime.

Do you have something semi generic you'd like to share for faster boxes?

**Comment by viptampa** [comment]
Yea, Sure, there are a few... do you want something that will QOS by data type, or by source/destination?

**Comment by Lillecarl** [comment]
Anything's good to get people started with QoS.07.05.2018, 02:31, "viptampa" <notifications@github.com>:Yea, Sure, there are a few... do you want something that will QOS by data type, or by source/destination?

**Comment by viptampa** [comment]
I'll pump out a script this weekend.

**Comment by Lillecarl** [comment]
Something with PCQ would be cool :)

**Comment by Lillecarl** [comment]
@viptampa You've had some time to put some QoS together now! ;)

One thing people seem to forget about MikroTik though is that you'll shoot yourself in the foot (like C++) if you're trying to shape a 100Mbps link with something weak like a hAP, you'll fuck the CPU over and create lag that way instead. It'd be nice if MikroTik, or the community could pool together some information on what devices are required to shape what traffic.

**Comment by Lillecarl** [comment]
Closed because of inactivity
